package kr.pincoin.api.domain.order.model

import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.*

class Order private constructor(
    val id: Long? = null,
    val created: LocalDateTime? = null,
    val modified: LocalDateTime? = null,
    val isRemoved: Boolean = false,
    val orderNo: UUID = UUID.randomUUID(),
    val userAgent: String = "",
    val acceptLanguage: String = "",
    val ipAddress: String,
    val paymentMethod: Int = 0,
    val status: Int = 0,
    val totalListPrice: BigDecimal = BigDecimal.ZERO,
    val totalSellingPrice: BigDecimal = BigDecimal.ZERO,
    val currency: String = "KRW",
    val message: String = "",
    val parentId: Long? = null,
    val userId: Int? = null,
    val fullname: String,
    val transactionId: String = "",
    val visible: Int = 1,
    val suspicious: Boolean = false,
) {
    private fun copy(
        isRemoved: Boolean = this.isRemoved,
        orderNo: UUID = this.orderNo,
        userAgent: String = this.userAgent,
        acceptLanguage: String = this.acceptLanguage,
        ipAddress: String = this.ipAddress,
        paymentMethod: Int = this.paymentMethod,
        status: Int = this.status,
        totalListPrice: BigDecimal = this.totalListPrice,
        totalSellingPrice: BigDecimal = this.totalSellingPrice,
        currency: String = this.currency,
        message: String = this.message,
        parentId: Long? = this.parentId,
        userId: Int? = this.userId,
        fullname: String = this.fullname,
        transactionId: String = this.transactionId,
        visible: Int = this.visible,
        suspicious: Boolean = this.suspicious,
    ): Order = Order(
        id = this.id,
        created = this.created,
        modified = this.modified,
        isRemoved = isRemoved,
        orderNo = orderNo,
        userAgent = userAgent,
        acceptLanguage = acceptLanguage,
        ipAddress = ipAddress,
        paymentMethod = paymentMethod,
        status = status,
        totalListPrice = totalListPrice,
        totalSellingPrice = totalSellingPrice,
        currency = currency,
        message = message,
        parentId = parentId,
        userId = userId,
        fullname = fullname,
        transactionId = transactionId,
        visible = visible,
        suspicious = suspicious,
    )

    companion object {
        fun of(
            id: Long? = null,
            created: LocalDateTime? = null,
            modified: LocalDateTime? = null,
            isRemoved: Boolean = false,
            orderNo: UUID = UUID.randomUUID(),
            userAgent: String = "",
            acceptLanguage: String = "",
            ipAddress: String,
            paymentMethod: Int = 0,
            status: Int = 0,
            totalListPrice: BigDecimal = BigDecimal.ZERO,
            totalSellingPrice: BigDecimal = BigDecimal.ZERO,
            currency: String = "KRW",
            message: String = "",
            parentId: Long? = null,
            userId: Int? = null,
            fullname: String,
            transactionId: String = "",
            visible: Int = 1,
            suspicious: Boolean = false,
        ): Order = Order(
            id = id,
            created = created,
            modified = modified,
            isRemoved = isRemoved,
            orderNo = orderNo,
            userAgent = userAgent,
            acceptLanguage = acceptLanguage,
            ipAddress = ipAddress,
            paymentMethod = paymentMethod,
            status = status,
            totalListPrice = totalListPrice,
            totalSellingPrice = totalSellingPrice,
            currency = currency,
            message = message,
            parentId = parentId,
            userId = userId,
            fullname = fullname,
            transactionId = transactionId,
            visible = visible,
            suspicious = suspicious,
        )
    }
}