package kr.pincoin.api.domain.inventory.model

import java.math.BigDecimal
import java.time.LocalDateTime

class Product private constructor(
    val id: Long? = null,
    val created: LocalDateTime? = null,
    val modified: LocalDateTime? = null,
    val isRemoved: Boolean = false,
    val name: String,
    val subtitle: String = "",
    val code: String,
    val listPrice: BigDecimal,
    val sellingPrice: BigDecimal,
    val description: String = "",
    val position: Int = 0,
    val status: Int = 0,
    val stock: Int = 0,
    val categoryId: Long,
    val storeId: Long,
    val reviewCount: Int = 0,
    val naverPartner: Boolean = false,
    val naverPartnerTitle: String = "",
    val minimumStockLevel: Int = 0,
    val pg: Boolean = false,
    val pgSellingPrice: BigDecimal = BigDecimal.ZERO,
    val naverAttribute: String = "",
    val naverPartnerTitlePg: String = "",
    val reviewCountPg: Int = 0,
    val maximumStockLevel: Int = 0,
    val stockQuantity: Int = 0,
) {
    companion object {
        fun of(
            id: Long? = null,
            created: LocalDateTime? = null,
            modified: LocalDateTime? = null,
            isRemoved: Boolean = false,
            name: String,
            subtitle: String = "",
            code: String,
            listPrice: BigDecimal,
            sellingPrice: BigDecimal,
            description: String = "",
            position: Int = 0,
            status: Int = 0,
            stock: Int = 0,
            categoryId: Long,
            storeId: Long,
            reviewCount: Int = 0,
            naverPartner: Boolean = false,
            naverPartnerTitle: String = "",
            minimumStockLevel: Int = 0,
            pg: Boolean = false,
            pgSellingPrice: BigDecimal = BigDecimal.ZERO,
            naverAttribute: String = "",
            naverPartnerTitlePg: String = "",
            reviewCountPg: Int = 0,
            maximumStockLevel: Int = 0,
            stockQuantity: Int = 0,
        ): Product = Product(
            id = id,
            created = created,
            modified = modified,
            isRemoved = isRemoved,
            name = name,
            subtitle = subtitle,
            code = code,
            listPrice = listPrice,
            sellingPrice = sellingPrice,
            description = description,
            position = position,
            status = status,
            stock = stock,
            categoryId = categoryId,
            storeId = storeId,
            reviewCount = reviewCount,
            naverPartner = naverPartner,
            naverPartnerTitle = naverPartnerTitle,
            minimumStockLevel = minimumStockLevel,
            pg = pg,
            pgSellingPrice = pgSellingPrice,
            naverAttribute = naverAttribute,
            naverPartnerTitlePg = naverPartnerTitlePg,
            reviewCountPg = reviewCountPg,
            maximumStockLevel = maximumStockLevel,
            stockQuantity = stockQuantity,
        )
    }
}