package kr.pincoin.api.domain.inventory.model

import kr.pincoin.api.domain.inventory.enums.ProductStatus
import kr.pincoin.api.domain.inventory.enums.ProductStock
import java.math.BigDecimal
import java.time.LocalDateTime

class Product private constructor(
    val id: Long? = null,
    val created: LocalDateTime? = null,
    val modified: LocalDateTime? = null,
    val isRemoved: Boolean = false,
    val name: String,
    val subtitle: String = "",
    val code: String,
    val listPrice: BigDecimal,
    val sellingPrice: BigDecimal,
    val description: String = "",
    val position: Int = 0,
    val status: ProductStatus = ProductStatus.ENABLED,
    val stock: ProductStock = ProductStock.SOLD_OUT,
    val categoryId: Long,
    val storeId: Long,
    val reviewCount: Int = 0,
    val naverPartner: Boolean = false,
    val naverPartnerTitle: String = "",
    val minimumStockLevel: Int = 0,
    val pg: Boolean = false,
    val pgSellingPrice: BigDecimal = BigDecimal.ZERO,
    val naverAttribute: String = "",
    val naverPartnerTitlePg: String = "",
    val reviewCountPg: Int = 0,
    val maximumStockLevel: Int = 0,
    val stockQuantity: Int = 0,
) {
    private fun copy(
        isRemoved: Boolean = this.isRemoved,
        name: String = this.name,
        subtitle: String = this.subtitle,
        code: String = this.code,
        listPrice: BigDecimal = this.listPrice,
        sellingPrice: BigDecimal = this.sellingPrice,
        description: String = this.description,
        position: Int = this.position,
        status: ProductStatus = this.status,
        stock: ProductStock = this.stock,
        categoryId: Long = this.categoryId,
        storeId: Long = this.storeId,
        reviewCount: Int = this.reviewCount,
        naverPartner: Boolean = this.naverPartner,
        naverPartnerTitle: String = this.naverPartnerTitle,
        minimumStockLevel: Int = this.minimumStockLevel,
        pg: Boolean = this.pg,
        pgSellingPrice: BigDecimal = this.pgSellingPrice,
        naverAttribute: String = this.naverAttribute,
        naverPartnerTitlePg: String = this.naverPartnerTitlePg,
        reviewCountPg: Int = this.reviewCountPg,
        maximumStockLevel: Int = this.maximumStockLevel,
        stockQuantity: Int = this.stockQuantity,
    ): Product = Product(
        id = this.id,
        created = this.created,
        modified = this.modified,
        isRemoved = isRemoved,
        name = name,
        subtitle = subtitle,
        code = code,
        listPrice = listPrice,
        sellingPrice = sellingPrice,
        description = description,
        position = position,
        status = status,
        stock = stock,
        categoryId = categoryId,
        storeId = storeId,
        reviewCount = reviewCount,
        naverPartner = naverPartner,
        naverPartnerTitle = naverPartnerTitle,
        minimumStockLevel = minimumStockLevel,
        pg = pg,
        pgSellingPrice = pgSellingPrice,
        naverAttribute = naverAttribute,
        naverPartnerTitlePg = naverPartnerTitlePg,
        reviewCountPg = reviewCountPg,
        maximumStockLevel = maximumStockLevel,
        stockQuantity = stockQuantity,
    )

    companion object {
        fun of(
            id: Long? = null,
            created: LocalDateTime? = null,
            modified: LocalDateTime? = null,
            isRemoved: Boolean = false,
            name: String,
            subtitle: String = "",
            code: String,
            listPrice: BigDecimal,
            sellingPrice: BigDecimal,
            description: String = "",
            position: Int = 0,
            status: ProductStatus = ProductStatus.ENABLED,
            stock: ProductStock = ProductStock.SOLD_OUT,
            categoryId: Long,
            storeId: Long,
            reviewCount: Int = 0,
            naverPartner: Boolean = false,
            naverPartnerTitle: String = "",
            minimumStockLevel: Int = 0,
            pg: Boolean = false,
            pgSellingPrice: BigDecimal = BigDecimal.ZERO,
            naverAttribute: String = "",
            naverPartnerTitlePg: String = "",
            reviewCountPg: Int = 0,
            maximumStockLevel: Int = 0,
            stockQuantity: Int = 0,
        ): Product = Product(
            id = id,
            created = created,
            modified = modified,
            isRemoved = isRemoved,
            name = name,
            subtitle = subtitle,
            code = code,
            listPrice = listPrice,
            sellingPrice = sellingPrice,
            description = description,
            position = position,
            status = status,
            stock = stock,
            categoryId = categoryId,
            storeId = storeId,
            reviewCount = reviewCount,
            naverPartner = naverPartner,
            naverPartnerTitle = naverPartnerTitle,
            minimumStockLevel = minimumStockLevel,
            pg = pg,
            pgSellingPrice = pgSellingPrice,
            naverAttribute = naverAttribute,
            naverPartnerTitlePg = naverPartnerTitlePg,
            reviewCountPg = reviewCountPg,
            maximumStockLevel = maximumStockLevel,
            stockQuantity = stockQuantity,
        )
    }
}