name: Build for production

on:
  workflow_dispatch:
# 자동 빌드 안 함
#  push:
#    branches: [ main ]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: [ self-hosted, Production ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # git pull 효과

      - name: Build Docker image
        run: |
          echo "🔨 Building Docker image with GitHub Dockerfile..."
          docker build -f Dockerfile.prod -t pincoin-backend:latest .