name: Build for production

on:
  workflow_dispatch:
# 자동 빌드 안 함
#  push:
#    branches: [ main ]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: [ self-hosted, Production ]
    steps:
      - name: Execute build script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PINCOIN_SERVER_HOST }}
          username: ${{ secrets.PINCOIN_USERNAME }}
          key: ${{ secrets.PINCOIN_SSH_KEY }}
          port: ${{ secrets.PINCOIN_SERVER_PORT }}
          script: |
            cd /opt/docker/pincoin/backend
            bash ./build.sh